apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: dba-qa-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: dba-qa
    server: https://kubernetes.default.svc
  project: dba-infra
  source:
    path: environments/dba-qa
    repoURL: https://github.com/ibm-cloud-architecture/dba-infra-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
